### ISSUE TITLE
Sinkhorn values

### ISSUE THREAD

**Issue by Eandrejczuk** [google-research/ott#10]
Hi,

I'm calculating Wasserstein distance using Sinkhorn approximation between two observations (no matching, just pure L2 distance). I see that the distance is way higher compared to the distance calculated by other methods (OT library, L2 norm).  In particular, I have embeddings of two 18-bit observations that vary by one bit. Thus, the distance between them should be low. 

The results are as follows:
L2 distance:  3.464944 (calculation: np.sqrt(np.sum(np.square(obs_standard-obs_terminal))))
OTT Sinkhorn distance:  12.005859

I would like to know where the difference is coming from.

Thanks!

**Comment by marcocuturi** [comment]
Hi Ewa,
Thanks for your message and for raising this issue.

It seems this issue comes from the fact that the sinkhorn implementation in OTT does *not* carry out a square root renormalization. For instance, when the cost is the squared euclidean distance, c(x, y) = || x - y ||^2, ``reg_ot_cost`` returns

``reg_ot_cost `` = min_{P} <P, ||x_i -y_j ||^2> - 𝜀 KL(P ||ab') 

and not. (min_{P} <P, ||x_i -y_j ||^2> - 𝜀 KL(P ||ab') )^{1/2} as is needed to define something that would look like a Wasserstein W_2 distance. If you wish to approximate the W_2 distance, you should compute the ``sinkhorn_divergence``, and take its square root, ``jnp.sqrt(divergence)``. 

Thanks a lot for point this out, a clarifying statement in the pydoc of ``sinkhorn`` and ``sinkhorn_divergence`` is needed :)
