### ISSUE TITLE
Sinkhorn's reg_ot_cost can be nan, when converged

### ISSUE THREAD

**Issue by ersisimou** [google-research/ott#5]
Hello and many thanks for this package!

I noticed that in the point_clouds jupyter notebook, that you provide in the documentation, after executing: 
out = sinkhorn.sinkhorn(geom, a, b) 

one gets:
out.reg_ot_cost -->  DeviceArray(nan, dtype=float32)

although out.converged is True and out.f, out.g have no nan values.

Setting epsilon to larger values, overcomes this issue. However, I was wondering if you clarify why the OT objective returns nan, although Sinkhorn seems to have run with no numerical issues.

Thanks in advance.

**Comment by ersisimou** [comment]
Issue seems to be resolved by setting the environment variable JAX_ENABLE_X64=True.

**Comment by marcocuturi** [comment]
Thanks Effrosyni for the heads up! good to know that our example would not work on np.float32. We may want to set the default epsilon on the example large enough so that it works independently of that.

**Comment by marcocuturi** [comment]
Hi @ersisimou , you might have experienced the bug for a reason that's not only related to np.float32, but also because we were computing the objective with a different approach in the most recent releases. This was possibly causing a bug for small epsilon's. Hopefully it should work again, even in 32.

**Comment by ersisimou** [comment]
Hi @marcocuturi , many thanks for letting me know! I will try again with the latest release.
